### ISSUE TITLE
"Innersource -> Does your organization have" should allow for no response

### ISSUE THREAD

**Issue by finos-admin** [finos-labs/osmm#21]
Either we add an option "None of the above" or we make the question not mandatory. 

Currently it doesn't allow submitting the form unless an option is selected (See screenshot below), and it's perfectly OK for it to be blank.

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/37706051/185003347-0d4c5581-931e-4f83-ad2d-9bf291ff96a0.png">

**Comment by mcleo-d** [comment]
Hi @padmalava - Can you update or close this issue with @finos-admin.

Many thanks,

James.

**Comment by padmalava** [comment]
I will change the question to "optional" as adding option "None of the above" would make the response more ambiguous: in cases where user chooses multiple options along with "None of the above"

**Comment by padmalava** [comment]
Issue Fixed in PR #25

**Comment by mcleo-d** [comment]
Fantastic @padmalava - Thank you!
