### ISSUE TITLE
Right structure for Docusaurus microsite from docs?

### ISSUE THREAD

**Issue by copiesofcopies** [finos-labs/osmm#5]
The documentation contributed is a mix of straight Github markdown and Docusaurus docs format. 

@mindthegab please advise whether you want OSMM to have its own microsite or be located on the OSR microsite. 

@maoo and/or @TheJuanAndOnly99 please assist the contributor in implementing @mindthegab's preference.

**Comment by mindthegab** [comment]
@copiesofcopies is this still needed?

**Comment by copiesofcopies** [comment]
@mindthegab I think it's something we can think about when the project gets out of labs.
