### ISSUE TITLE
OSMM Logo?

### ISSUE THREAD

**Issue by mindthegab** [finos-labs/osmm#9]
@padmalava @vmbrasseur do you know if a logo already exists for OSMM?

If not, @mcleo-d could get the internal process started?

Thanks!

**Comment by vmbrasseur** [comment]
To the best of my knowledge, there isn't a logo for the OSMM yet.

**Comment by mcleo-d** [comment]
This is now work in progress.

**Comment by gravax** [comment]
This is amazing news. One comment... On the vertical version, if you zoom heavily, the word "MATURITY" isn't aligned to the left like "OPEN" or even the logo. There's a space. Might be worth asking the designer to edit it for precision...

**Comment by padmalava** [comment]
I am getting a permission issue while uploading the theme

[Error](https://github.com/padmalava/osmm/blob/main/Screenshot%202022-11-28%20121332.png)

Incorrect permissions in your "/opt/bitnami/limesurvey/upload/themes/survey" folder

@maoo  Could you check the permission please?

**Comment by maoo** [comment]
Here the permissions:

```
ls -la /opt/bitnami/limesurvey/upload/themes/survey
drwxr-xr-x 3 bitnami bitnami 4096 Nov 15 11:15 .
drwxr-xr-x 4 bitnami bitnami 4096 Nov 15 11:15 ..
drwxr-xr-x 2 bitnami bitnami 4096 Nov 15 11:15 generalfiles
-rwxr-xr-x 1 bitnami bitnami  255 Nov 15 11:15 index.html
```

@padmalava - could you please tell me which permissions you need me to apply? TY

**Comment by mcleo-d** [comment]
> This is amazing news. One comment... On the vertical version, if you zoom heavily, the word "MATURITY" isn't aligned to the left like "OPEN" or even the logo. There's a space. Might be worth asking the designer to edit it for precision...
> 
> [Sample Image](https://i.ibb.co/5xx1fgZ/2022-11-25-1.png)

Hi @gravax - Thanks for your trained design eyes on the logo. At the moment the priority is getting the horizontal logo applied on the OSMM build ready for beta launch.

Once this is done, I'll pass your feedback to the designer to apply.

Thanks for your time :)

James.

**Comment by padmalava** [comment]
Logo has been updated
